---
- hosts: web
  tasks:
  - name: Unregister Red Hat subscription
    state: absent

- hosts: web
  tasks:
  - name: Register with activationkey and consume subscriptions 
    redhat_subscription:
      state: present
      activationkey: 'idm-lab-temp'
      org_id: '12451665'
      force_register: yes
