---
- hosts: all
  tasks:
  - name: Update all packages
    yum:
      name: "*"
      state: latest

- hosts: web
  tasks: 
  - name: Update hostnames 
  - hostname: 
       name: "{{ item }}"
       loop:
        - host02.test.local
        - host03.test.local
