---
- hosts: web
  tasks:
    - name: Update Hostnames
      hostname:
        name: "{{ new_hostname }}"
        
- hosts: all
  tasks:
  - name: add hostname to /etc/hosts
    vars:
      comment: '# added by ansible'
    lineinfile:
      dest: /etc/hosts
      regexp: "127[.]0[.]0[.]1.*"
      line: "127.0.0.1 localhost.localdomain localhost {{ ansible_hostname }} {{ comment }}"
      state: present
      backup: yes
    - name: Add IP address of all hosts to all hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item].ansible_host }} {{item}}"
        state: present
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups.all }}"

- hosts: all
  tasks:
  - name: Update all packages
    yum:
      name: "*"
      state: latest
