---
#- hosts: all
#  tasks:
#  - name: Update all packages
#    yum:
#      name: "*"
#      state: latest

- hosts: web
  tasks: 
  - hostname: 
       name: "{{ item.name }}"
       loop:
        - {name: host02.test.local, message: host02_done}
        - {name: host03.test.local, message: host03_done}
       loop_control:
        label: "{{ item.message }}"
